use_frameworks!

def standard_pods
    pod 'DDSpiderChart', :path => '../'
end

target 'DDSpiderChart_Example' do
    standard_pods
end

target 'DDSpiderChart_Tests' do
    inherit! :search_paths
    standard_pods
end
