platform :ios, '8.0'

use_frameworks!

def standard_pods
    pod 'DDSpiderChart', :path => '../'
end

target 'DDSpiderChart_Example' do
    standard_pods
end

target 'DDSpiderChart_Tests' do
    platform :ios, '11.0'
  
    inherit! :search_paths
    standard_pods
    
    pod 'SnapshotTesting'
end
